# Generated by Django 3.0 on 2019-12-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
