# Generated by Django 3.0 on 2019-12-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0003_auto_20191230_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objectiu',
            new_name='Goal',
        ),
    ]
