# Generated by Django 3.0 on 2019-12-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0004_auto_20191210_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendance',
        ),
    ]
