# Generated by Django 3.0 on 2019-12-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0004_auto_20191230_1059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Explicacio',
            new_name='Schedule',
        ),
    ]
