# Generated by Django 3.0 on 2019-12-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0005_auto_20191230_1105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cours',
            new_name='Course',
        ),
    ]
