# Generated by Django 3.0 on 2019-12-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0005_remove_event_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='rate',
            new_name='activity_rate',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='description',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='rate',
            name='circle_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='line_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='respect_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='snack_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
