# Generated by Django 3.0 on 2019-12-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0006_auto_20191230_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
    ]
