# Generated by Django 3.0 on 2019-12-11 10:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voluntariapp', '0007_auto_20191210_1607'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventattendee',
            unique_together={('user', 'event')},
        ),
    ]
