# Generated by Django 3.0 on 2019-12-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0007_remove_event_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='activity_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
