# Generated by Django 3.0 on 2020-01-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0008_event_activity_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendee',
            name='attendance_control',
            field=models.BooleanField(default=False),
        ),
    ]
