# Generated by Django 3.0 on 2019-12-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0008_auto_20191211_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendee',
            name='attending',
        ),
    ]
