# Generated by Django 3.0 on 2020-01-06 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0009_eventattendee_attendance_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rate',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voluntariapp.Event'),
        ),
    ]
