# Generated by Django 3.0 on 2019-12-11 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0009_remove_eventattendee_attending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voluntariapp.Event'),
        ),
    ]
