# Generated by Django 3.0 on 2019-12-11 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0011_auto_20191211_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voluntariapp.Cours')),
            ],
        ),
        migrations.CreateModel(
            name='Setmana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('rate_avg', models.IntegerField(blank=True, null=True)),
                ('attendance_avg', models.IntegerField(blank=True, null=True)),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voluntariapp.Quarter')),
            ],
        ),
    ]
