# Generated by Django 3.0 on 2020-01-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0011_rate_total_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='attendance_avg',
        ),
        migrations.RemoveField(
            model_name='week',
            name='rate_avg',
        ),
    ]
