# Generated by Django 3.0 on 2019-12-11 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0014_auto_20191211_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='setmana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setmana_id', to='voluntariapp.Setmana'),
        ),
    ]
