# Generated by Django 3.0 on 2019-12-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0015_auto_20191211_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='setmana',
        ),
    ]
