# Generated by Django 3.0 on 2019-12-16 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voluntariapp', '0017_auto_20191211_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('group', models.TextField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forumtopic_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='forumtheme',
        ),
        migrations.DeleteModel(
            name='ForumTheme',
        ),
        migrations.AddField(
            model_name='comment',
            name='forumtopic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voluntariapp.ForumTopic'),
            preserve_default=False,
        ),
    ]
