# Generated by Django 3.0 on 2019-12-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0019_auto_20191216_1127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setmana',
            new_name='Week',
        ),
    ]
