# Generated by Django 3.0 on 2019-12-16 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0020_auto_20191216_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreinteres',
            name='cours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voluntariapp.Cours'),
            preserve_default=False,
        ),
    ]
