# Generated by Django 3.0 on 2019-12-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0022_explicacio_objectius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centreinteres',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
