# Generated by Django 3.0 on 2019-12-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0023_auto_20191217_0848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objectius',
            new_name='Objectiu',
        ),
    ]
