# Generated by Django 3.0 on 2019-12-19 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0026_auto_20191219_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='week_id', to='voluntariapp.Week'),
            preserve_default=False,
        ),
    ]
