# Generated by Django 3.0 on 2019-12-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0029_auto_20191223_1058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
