# Generated by Django 3.0 on 2019-12-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariapp', '0030_auto_20191223_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.CharField(blank=True, max_length=9)),
                ('days', models.CharField(max_length=5)),
            ],
        ),
    ]
